services:
  django:
    build:
      context: .
    expose:
      - 8000
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "8000:80"
    depends_on:
      - django
    restart: always

volumes:
  nginx_logs:
