# Generated by Django 5.1.3 on 2024-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoicedetailsmodel_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
