# Generated by Django 5.1.3 on 2024-11-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoicemodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='date',
        ),
    ]
