# Generated by Django 5.1.3 on 2024-11-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_invoicemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
